### ISSUE TITLE
Sleep 1 minute?

### ISSUE THREAD

**Issue by paulroth3d** [kevinohara80/salesforcedx-circleci-demo#2]
This really is awesome Kevin - thanks so much for putting this together.

Just to ask - and I think I might already know - the sleep 1m command in the circle.yml - have you found any other way around it? (or is sleeping a minute the best option we have right now)

**Comment by kevinohara80** [comment]
I honestly don't remember why I put that in there. :)

What was your understanding for the need to have a sleep step?
